[package]
name = "eve-esi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
chrono = "0.4.35"
serde = { version = "1.0.197", features = ["serde_derive"] }
serde_json = "1.0.114"
reqwest = { version="0.12.0", features=["json"] }
tracing = "0.1.40"
