apiVersion: v1
kind: Namespace
metadata:
  name: womptools
  labels:
    name: womptools
---
apiVersion: v1
kind: Namespace
metadata:
  name: womptools-monitoring
  labels:
    name: womptools-monitoring
