apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: womptools-monitoring
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        env:
        - name: "COLLECTOR_OTLP_ENABLED"
          value: "true"
        - name: "METRICS_STORAGE_TYPE"
          value: "prometheus"
        - name: "PROMETHEUS_SERVER_URL"
          value: "http://prometheus-cip:9090"
        - name: "PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR"
          value: "true"
        - name: "PROMETHEUS_QUERY_NORMALIZE_CALLS"
          value: "true"
        - name: "PROMETHEUS_QUERY_NORMALIZE_DURATION"
          value: "true"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 4317 # collector - OTLP gRPC
          protocol: TCP
        - containerPort: 4318 # collector - OTLP HTTP
          protocol: TCP
        # - containerPort: 5778 # agent - serve configs
        #   protocol: TCP
        # - containerPort: 6831 # agent - jaeger.thrift (compact)
        #   protocol: UDP
        # - containerPort: 6832 # agent - jaeger.thrift (binary)
        #   protocol: UDP
        # - containerPort: 9411 # collector zipkin endpoint
        #   protocol: TCP
        # - containerPort: 14250 # collector - model.proto
        #   protocol: TCP
        # - containerPort: 14268 # collector - jaeger.thrift
        #   protocol: TCP
        - containerPort: 16686 # query - frontend
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-cip
  namespace: womptools-monitoring
spec:
  type: ClusterIP
  selector:
    app: jaeger
  ports:
    - port: 4317
      name: jaeger-collector-otlp-grpc
      protocol: TCP
    - port: 4318
      name: jaeger-collector-otlp-http
      protocol: TCP
    # - port: 5778
    #   name: jaeger-agent-configs
    #   protocol: TCP
    # - port: 6831
    #   name: jaeger-agent-thrift-compact
    #   protocol: UDP
    # - port: 6832
    #   name: jaeger-agent-thrift-binary
    #   protocol: UDP
    # - port: 9411
    #   name: jaeger-collector-zipkin
    #   protocol: TCP
    # - port: 14250
    #   name: jaeger-collector-model-proto
    #   protocol: TCP
    # - port: 14268
    #   name: jaeger-collector-thrift
    #   protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-port
  namespace: womptools-monitoring
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
    - name: jaeger-frontend-port
      protocol: TCP
      port: 16686
