apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-configuration
  namespace: womptools-monitoring
data:
  otel-config.yml: |
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14260
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      prometheus:
        endpoint: 0.0.0.0:8889
      otlp:
        endpoint: jaeger-cip:4317
        tls:
          insecure: true
    connectors:
      spanmetrics:
    processors:
      batch:
    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: [batch]
          exporters: [spanmetrics, otlp]
        metrics/spanmetrics:
          receivers: [spanmetrics]
          exporters: [prometheus]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel
  namespace: womptools-monitoring
spec:
  selector:
    matchLabels:
      app: otel
  template:
    metadata:
      labels:
        app: otel
    spec:
      volumes:
        - name: otel-config-volume
          configMap:
            name: otel-configuration
            defaultMode: 420
      containers:
        - name: otel
          image: otel/opentelemetry-collector-contrib:latest
          args: ["--config", "/etc/otelcol/otel-config.yml"]
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8888   # metrics
              protocol: TCP
            - containerPort: 4317   # otel grpc
              protocol: TCP
            - containerPort: 4318   # otel http
              protocol: TCP
            - containerPort: 14260  # receivers - jaeger/grpc
              protocol: TCP
            - containerPort: 8889   # exporters - prometheus
              protocol: TCP
          volumeMounts:
            - name: otel-config-volume
              mountPath: /etc/otelcol
---
apiVersion: v1
kind: Service
metadata:
  name: otel-cip
  namespace: womptools-monitoring
spec:
  type: ClusterIP
  selector:
    app: otel
  ports:
    - name: otel-metrics
      port: 8888
      protocol: TCP
    - name: otel-receivers-jaeger-grpc
      port: 14260
      protocol: TCP
    - name: otel-exporters-prometheus
      port: 8889
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: otel-port
  namespace: womptools-monitoring
spec:
  type: NodePort
  selector:
    app: otel
  ports:
    - name: otel-grpc-port
      protocol: TCP
      port: 4317
    - name: otel-http-port
      protocol: TCP
      port: 4318
