apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: womptools
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: womptools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: mariadb_root_password
          resources:
            limits:
              memory: "512Mi"
              cpu: "300m"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-pv
      volumes:
        - name: mariadb-pv
          persistentVolumeClaim:
            claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-cip
  namespace: womptools
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
    - name: mariadb
      protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-port
  namespace: womptools
spec:
  type: NodePort
  selector:
    app: mariadb
  ports:
    - name: mariadb
      protocol: TCP
      port: 3306
      targetPort: 3306
