[package]
name = "service-sso-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
serde = { version = "1.0.197", features = ["serde_derive"] }
serde_json = "1.0.114"
reqwest = { version="0.12.0", features=["json"] }