
const names = new Map<string, string>([
    [ 'player_trading', 'Player Trading' ],
    [ 'market_transaction', 'Market Transaction' ],
    [ 'gm_cash_transfer', 'GM Cash Transfer' ],
    [ 'mission_reward', 'Mission Reward' ],
    [ 'clone_activation', 'Clone Activation Fee' ],
    [ 'inheritance', 'Inheritance' ],
    [ 'player_donation', 'Player Donation' ],
    [ 'corporation_payment', 'Corporation Payment' ],
    [ 'docking_fee', 'Docking Fee' ],
    [ 'office_rental_fee', 'Office Rental Fee' ],
    [ 'factory_slot_rental_fee', 'Factory Slot Rental Fee' ],
    [ 'repair_bill', 'Repair Bill' ],
    [ 'bounty', 'Bounty' ],
    [ 'bounty_prize', 'Bounty Prize' ],
    [ 'insurance', 'Insurance' ],
    [ 'mission_expiration', 'Mission Expiration' ],
    [ 'mission_completion', 'Mission Completion' ],
    [ 'shares', 'shares' ],
    [ 'courier_mission_escrow', 'Courier Mission Escrow' ],
    [ 'mission_cost', 'Mission Cost' ],
    [ 'agent_miscellaneous', 'Agent Misc' ],
    [ 'lp_store', 'LP Store' ],
    [ 'agent_location_services', 'Agent Location Services' ],
    [ 'agent_donation', 'Agent Donation' ],
    [ 'agent_security_services', 'Agent Security Services' ],
    [ 'agent_mission_collateral_paid', 'Agent Mission Collateral' ],
    [ 'agent_mission_collateral_refunded', 'Agent Mission Collateral Refund' ],
    [ 'agents_preward', 'Agent Reward' ],
    [ 'agent_mission_reward', 'Agent Mission Reward' ],
    [ 'agent_mission_time_bonus_reward', 'Agent Mission Bonus Reward' ],
    [ 'cspa', 'CSPA' ],
    [ 'cspaofflinerefund', 'CSPA Offline Refund' ],
    [ 'corporation_account_withdrawal', 'Corporation Account Withdrawal' ],
    [ 'corporation_dividend_payment', 'Corporation Dividend Payment' ],
    [ 'corporation_registration_fee', 'Corporation Registration Fee' ],
    [ 'corporation_logo_change_cost', 'Corporation Logo Cost' ],
    [ 'release_of_impounded_property', 'Release of Impounded Property' ],
    [ 'market_escrow', 'Market Escrow' ],
    [ 'agent_services_rendered', 'Agent Services' ],
    [ 'market_fine_paid', 'Marked Fine' ],
    [ 'corporation_liquidation', 'Corporation Liquidation' ],
    [ 'brokers_fee', 'Brokers Fee' ],
    [ 'corporation_bulk_payment', 'Corporation Bulk Playment' ],
    [ 'alliance_registration_fee', 'Alliance Registration Fee' ],
    [ 'war_fee', 'War Fee' ],
    [ 'alliance_maintainance_fee', 'Alliance Maintenance fee' ],
    [ 'contraband_fine', 'Contraband Fee' ],
    [ 'clone_transfer', 'Clone Transfer' ],
    [ 'acceleration_gate_fee', 'Acceleration Gate Fee' ],
    [ 'transaction_tax', 'Transaction Tax' ],
    [ 'jump_clone_installation_fee', 'Jump Clone Installation Fee' ],
    [ 'manufacturing', 'Manufacturing' ],
    [ 'researching_technology', 'Research Technology' ],
    [ 'researching_time_productivity', 'Research Time Productivity' ],
    [ 'researching_material_productivity', 'Research Material Productivity' ],
    [ 'copying', 'Copying' ],
    [ 'reverse_engineering', 'Reverse Engineering' ],
    [ 'contract_auction_bid', 'Contract Auction Bid' ],
    [ 'contract_auction_bid_refund', 'Contract Auction Bid Refund' ],
    [ 'contract_collateral', 'Contract Collateral' ],
    [ 'contract_reward_refund', 'Contract Reward Refund' ],
    [ 'contract_auction_sold', 'Contract Auction Sold' ],
    [ 'contract_reward', 'Contract Reward' ],
    [ 'contract_collateral_refund', 'Contract Collateral Refund' ],
    [ 'contract_collateral_payout', 'Contract Collateral Payout' ],
    [ 'contract_price', 'Contract Price' ],
    [ 'contract_brokers_fee', 'Contract Brokers Fee' ],
    [ 'contract_sales_tax', 'Contract Sales Tax' ],
    [ 'contract_deposit', 'Contract Deposit' ],
    [ 'contract_deposit_sales_tax', 'Contract Deposit Sales Tax' ],
    [ 'contract_auction_bid_corp', 'Contract Auction Bid' ],
    [ 'contract_collateral_deposited_corp', 'Contract Collateral Deposited' ],
    [ 'contract_price_payment_corp', 'Contract Price Payment' ],
    [ 'contract_brokers_fee_corp', 'Contract Brokers Fee' ],
    [ 'contract_deposit_corp', 'Contract Deposit' ],
    [ 'contract_deposit_refund', 'Contract Deposit Refund' ],
    [ 'contract_reward_deposited', 'Contract Reward Deposited' ],
    [ 'contract_reward_deposited_corp', 'Contract Reward Deposited' ],
    [ 'bounty_prizes', 'Bounty Prizes' ],
    [ 'advertisement_listing_fee', 'Advertisement Listing Fee' ],
    [ 'medal_creation', 'Medal Creation' ],
    [ 'medal_issued', 'Medal Issued' ],
    [ 'dna_modification_fee', 'DNA Modification Fee' ],
    [ 'sovereignity_bill', 'Sovereignity Bill' ],
    [ 'bounty_prize_corporation_tax', 'Bounty Prize Corporation Tax' ],
    [ 'agent_mission_reward_corporation_tax', 'Agent Mission Reward Tax' ],
    [ 'agent_mission_time_bonus_reward_corporation_tax', 'Agent Mission Bonus Tax' ],
    [ 'upkeep_adjustment_fee', 'Upkeep Adjustment Fee' ],
    [ 'planetary_import_tax', 'Planetary Import Tax' ],
    [ 'planetary_export_tax', 'Planetary Export Tax' ],
    [ 'planetary_construction', 'Planetary Construction' ],
    [ 'corporate_reward_payout', 'Corporation Reward Payout' ],
    [ 'bounty_surcharge', 'Bounty Surcharge' ],
    [ 'contract_reversal', 'Contract Reversal' ],
    [ 'corporate_reward_tax', 'Corporation Reward Tax' ],
    [ 'store_purchase', 'Store Purchase' ],
    [ 'store_purchase_refund', 'Store Purchase Refund' ],
    [ 'datacore_fee', 'Datecore Fee' ],
    [ 'war_fee_surrender', 'War Fee Surrender' ],
    [ 'war_ally_contract', 'War Ally Contract' ],
    [ 'bounty_reimbursement', 'Bounty Reimbursement' ],
    [ 'kill_right_fee', 'Kill Right Fee' ],
    [ 'security_processing_fee', 'Security Processing Fee' ],
    [ 'industry_job_tax', 'Industry Job Tax' ],
    [ 'infrastructure_hub_maintenance', 'Infrastructure Hub Maintenance' ],
    [ 'asset_safety_recovery_tax', 'Asset Safety Recovery Tax' ],
    [ 'opportunity_reward', 'Opportunity Reward' ],
    [ 'project_discovery_reward', 'Project Discovery Reward' ],
    [ 'project_discovery_tax', 'Project Discovery Tax' ],
    [ 'reprocessing_tax', 'Reprocessing Tax' ],
    [ 'jump_clone_activation_fee', 'Jump Clone Activation Fee' ],
    [ 'operation_bonus', 'Operation Bonus' ],
    [ 'resource_wars_reward', 'Resource Wars Reward' ],
    [ 'duel_wager_escrow', 'Duel Wager Escrow' ],
    [ 'duel_wager_payment', 'Duel Wager Payment' ],
    [ 'duel_wager_refund', 'Duel Wager Refund' ],
    [ 'reaction', 'Reaction' ],
    [ 'structure_gate_jump', 'Gate Activation Fee' ],
    [ 'external_trade_freeze', 'External Trade Freeze' ],
    [ 'external_trade_thaw', 'External Trade Thaw' ],
    [ 'external_trade_delivery', 'External Trade Delivery' ],
    [ 'season_challenge_reward', 'Season Challenge Reward' ],
    [ 'skill_purchase', 'Skill Purchase' ],
    [ 'item_trader_payment', 'Item Trader Payment' ],
    [ 'flux_ticket_sale', 'Flux Ticket Sale' ],
    [ 'flux_payout', 'Flux Payout' ],
    [ 'flux_tax', 'Flux Tax' ],
    [ 'flux_ticket_repayment', 'Flux Ticket Repayment' ],
    [ 'redeemed_isk_token', 'Redeemed ISK Token' ],
    [ 'daily_challenge_reward', 'Daily Challenge Reward' ],
    [ 'market_provider_tax', 'Market Provider Tax' ],
    [ 'ess_escrow_transfer', 'ESS Escrow Transfer' ],
    [ 'milestone_reward_payment', 'Milestone Reward Payment' ],
])

export default function formatJournalType(type: string): string {
    return names.get(type) ?? 'Unknown';
}